version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order-history-event:1:1"
  shipping-db:
    build: ../shipping/docker/database
    environment:
      POSTGRES_PASSWORD: shipass
      POSTGRES_USER: shipuser
    ports:
      - 5432:5432
  shipping:
    build: ../shipping
    depends_on:
      - kafka
      - shipping-db
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092